# Generated by Django 5.2.8 on 2025-11-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('bias', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('accuracy_flag', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('comment', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='stories.newsstory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
