# Generated by Django 5.2.8 on 2025-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
