# Generated by Django 5.2.8 on 2025-11-10 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Stories',
                'ordering': ['-published_at'],
            },
        ),
    ]
